
import type { Metadata } from "next";
import "./globals.css";
import Header from "./../components/Molecules/Header/Header";
import AppProvider from "./provider";
import StyledComponentsRegistry from "@/lib/registry";
import GlobalStyles from "@/styles/globalStyles";
import { OpenSans } from "@/styles/fonts";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <AppProvider>
      <html lang="en">
        <body className={OpenSans.className}>
      <GlobalStyles/>
          <StyledComponentsRegistry>
          <Header />{children}</StyledComponentsRegistry>
        </body>
      </html>
    </AppProvider>
  );
}
